### ISSUE TITLE
Please use a license that meets the Open Source Hardware Definition

### ISSUE THREAD

**Issue by penyuan** [LydByDissing/stroem#29]
Thanks for creating the Strøm! What an exciting project, really looking forward to seeing it grow.

I see that this project is currently licensed under the [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/) license. This is ***not*** an open source license. It does not meet the [Open Source Hardware Definition](https://www.oshwa.org/definition/), nor does it meet the [Open Source Definition](https://opensource.org/osd), both of which are the widely adopted industry standards.

Please change to a license that meets those definitions, such as one of the three industry-standard [CERN OHLv2](https://ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2) licenses. [Here](https://choosealicense.com/licenses/cern-ohl-s-2.0/) is an example on how to apply the CERN OHL v2 license.

Otherwise, the term "open source" should not be used to describe this product.

Thanks!

**Comment by TooDissing** [comment]
Thank you for mentioning this @penyuan. You are completely correct.
We are currently looking into the matter and the various open source licenses. We will choose a new license soon and update everything accordingly.

**Comment by penyuan** [comment]
Great to know that a true open source license is coming soon! Thank you @TooDissing! Looking forward to it.
